
name: Tac V1

on:
  push:
    branches: ["ui_refactor"]
    paths: ['docs/test_doc/tac_v1/**']
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm 9
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: "./docs/test_doc/tac_v1"
      - name: Build VitePress
        run: |
          pnpm install
          pnpm run build
        working-directory: ./docs/test_doc/tac_v1
      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./docs/test_doc/tac_v1/dist
          target-folder: tac_v1
